In [ ]:
import numpy as np

In [ ]:
# Array creation
shape = (3,4)
dtype = np.int32
order = 'C'

In [ ]:
# Creates array without initializing entries
array1 = np.empty(shape, dtype)
array1

array([[-2043364424,       32730,  1725429712,       21959],
       [          0,           0,           0,           0],
       [          0,           0,           0,           0]], dtype=int32)

In [ ]:
# Returns array with same shape and type as given array
array2 = np.empty_like(array1)
array2

array([[-2043364488,       32730, -2043364488,       32730],
       [          0,           0,           0,           0],
       [ 1760273608,       32730,  1760273672,       32730]], dtype=int32)

In [ ]:
# Returns a 2-D matrix with ones on diagonal and zeros elsewhere
array3 = np.eye(N=4)
print(array3)

array4 = np.eye(N=4,M=2)
print(array4)

array5 = np.eye(N=4, k=1)
print(array5)
# k defines the amount by which you want to shift the main diagonal

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]


In [ ]:
# To get a identity matrix
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [ ]:
np.ones((4,3,2), dtype=np.float32)

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]], dtype=float32)

In [ ]:
np.ones_like(array1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [ ]:
np.zeros_like(array1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [ ]:
np.zeros(shape)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
# To create an array with your specified value in all the cells
np.full((4,3), fill_value=10.)

array([[ 10.,  10.,  10.],
       [ 10.,  10.,  10.],
       [ 10.,  10.,  10.],
       [ 10.,  10.,  10.]])

In [ ]:
np.full_like(array1, fill_value=1+9j, dtype=complex)

array([[ 1.+9.j,  1.+9.j,  1.+9.j,  1.+9.j],
       [ 1.+9.j,  1.+9.j,  1.+9.j,  1.+9.j],
       [ 1.+9.j,  1.+9.j,  1.+9.j,  1.+9.j]])

In [ ]:
# So far we discussed a new array creation and 
# now we discuss how to create a new array using existing data
ref_array = 10*np.random.rand(3,4)
ref_array

array([[ 3.87194212,  6.0227274 ,  9.40008761,  1.55617568],
       [ 1.62449474,  8.24526602,  8.9153371 ,  0.13569454],
       [ 1.31895575,  5.89019258,  8.51156338,  2.12524318]])

In [ ]:
array1 = np.array(ref_array, dtype=np.int, copy=True, order='C')
print(array1)

# Now why we copied
array1[0,1] = 10
print(array1)
print(ref_array)

# Now if we didn't copy
array2 = np.array(ref_array, copy=False)
array2[0,2] = 15
print('\n', array2)

print(ref_array)
# As you can notice that if we didn.t copy than the array from which
# we copied also got the changes

[[ 3  6 15  1]
 [ 1  8  8  0]
 [ 1  5  8  2]]
[[ 3 10 15  1]
 [ 1  8  8  0]
 [ 1  5  8  2]]
[[  3.87194212   6.0227274   15.           1.55617568]
 [  1.62449474   8.24526602   8.9153371    0.13569454]
 [  1.31895575   5.89019258   8.51156338   2.12524318]]

 [[  3.87194212   6.0227274   15.           1.55617568]
 [  1.62449474   8.24526602   8.9153371    0.13569454]
 [  1.31895575   5.89019258   8.51156338   2.12524318]]
[[  3.87194212   6.0227274   15.           1.55617568]
 [  1.62449474   8.24526602   8.9153371    0.13569454]
 [  1.31895575   5.89019258   8.51156338   2.12524318]]


In [ ]:
# To create an array from objects that can be converted to arrays
# like lists, tuples, ndarrays
array2 = np.asarray(ref_array)
print(array2)

array3 = np.asarray([[4,5,6],[1,2,3]])
print(array3)

[[  3.87194212   6.0227274   15.           1.55617568]
 [  1.62449474   8.24526602   8.9153371    0.13569454]
 [  1.31895575   5.89019258   8.51156338   2.12524318]]
[[4 5 6]
 [1 2 3]]


In [ ]:
# To get a contiguous array in memory
array4 = np.ascontiguousarray(ref_array)
array4

array([[  3.87194212,   6.0227274 ,  15.        ,   1.55617568],
       [  1.62449474,   8.24526602,   8.9153371 ,   0.13569454],
       [  1.31895575,   5.89019258,   8.51156338,   2.12524318]])

In [ ]:
# To simply copy an array
array5 = np.copy(ref_array)
array5

array([[  3.87194212,   6.0227274 ,  15.        ,   1.55617568],
       [  1.62449474,   8.24526602,   8.9153371 ,   0.13569454],
       [  1.31895575,   5.89019258,   8.51156338,   2.12524318]])

In [ ]:
# if you want to create an array from a buffer say a srtring
dt = np.dtype(int)
dt = dt.newbyteorder('>')
np.frombuffer('hello', dtype=dt)

AttributeError: 'str' object has no attribute '__buffer__'

In [ ]:
# To create an array from a file
dt = np.dtype(int)
dt = dt.newbyteorder('>')
np.fromfile(file='vimTutorial.txt', dtype=dt)

array([5432882060864155506, 2336646335973647726, 8391061973054070892,
       7306655128079005285, 7882828167451910189, 2338616291577788005,
       2337208112243304814, 7286934626993310315, 2318545067618364783,
       8531260732088852588, 7597120811504241260, 2318545058932418676,
       2336646335973647726, 8361506904289124397, 4476706050239985769,
       8367818302828869481, 8388076856227689313, 8532472353939220577,
       7955438811540518769, 2318577692278988901, 8676593839527851109,
       8223699782014168679, 2334669371110750240, 3260078864715506789,
       7810777106429012069, 2333823799648150388, 7309940812453342836,
       7306000102812836725, 8247057878230919456, 3260078864715507557,
       8367804030775140457, 7958816508742757743, 7234224000819227936,
       8388065495758692722, 7017580623428612207, 7597137600240968313,
       2333838166331453962, 6998643565789474592, 7450488841110975599,
       2335519323670606880, 7885631858047087215, 7863412941110931045,
       8679597993174

In [ ]:
# To create a character array
np.chararray

TypeError: 'str' object cannot be interpreted as an integer

In [ ]:
# it creates an array from starting=1 to end=10 taking strides=3
np.arange(start=1, stop=10, step=3)

array([1, 4, 7])

In [ ]:
# To divide the number into equal number of sample
np.linspace(start=1,stop=10, num=10, endpoint=True)
# endp[oint specifies whether to include the endpoint in the smaples

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [ ]:
# To get numbers on a logspace
# It starts at base**start and ends with base**stop
array1= np.logspace(start=1, stop=10, num=10, endpoint=True, base=10)
print (array1, '\n')

array2 = np.logspace(start=1, stop=10, num=10, base=2)
print(array2)

[  1.00000000e+01   1.00000000e+02   1.00000000e+03   1.00000000e+04
   1.00000000e+05   1.00000000e+06   1.00000000e+07   1.00000000e+08
   1.00000000e+09   1.00000000e+10] 

[    2.     4.     8.    16.    32.    64.   128.   256.   512.  1024.]


In [ ]:
# Each output is a constant multiple of previous output
array3 = np.geomspace(start=1, stop=10, num=10)
print(array3, '\n')

for a in range(1,10):
    print(array3[a]/array3[a-1])

array4 = np.geomspace(start=1, stop=1000, num=4)
print('\n', array4)

[  1.           1.29154967   1.66810054   2.15443469   2.7825594
   3.59381366   4.64158883   5.9948425    7.74263683  10.        ] 

1.29154966501
1.29154966501
1.29154966501
1.29154966501
1.29154966501
1.29154966501
1.29154966501
1.29154966501
1.29154966501

 [    1.    10.   100.  1000.]


In [ ]:
# To extract a diagonal from a matrix
print(ref_array, '\n')

np.diag(ref_array, k=1)

[[  3.87194212   6.0227274   15.           1.55617568]
 [  1.62449474   8.24526602   8.9153371    0.13569454]
 [  1.31895575   5.89019258   8.51156338   2.12524318]] 



array([ 6.0227274 ,  8.9153371 ,  2.12524318])

In [ ]:
array5 = np.diagflat(ref_array , k=0)
for a in array5:
    print(a, '\n')

[ 3.87194212  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.        ] 

[ 0.         6.0227274  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.       ] 

[  0.   0.  15.   0.   0.   0.   0.   0.   0.   0.   0.   0.] 

[ 0.          0.          0.          1.55617568  0.          0.          0.
  0.          0.          0.          0.          0.        ] 

[ 0.          0.          0.          0.          1.62449474  0.          0.
  0.          0.          0.          0.          0.        ] 

[ 0.          0.          0.          0.          0.          8.24526602
  0.          0.          0.          0.          0.          0.        ] 

[ 0.         0.         0.         0.         0.         0.         8.9153371
  0.         0.         0.         0.         0.       ] 

[ 0.          0.          0.          0.          0.          0.          0.
  0.13569454  0.    

In [ ]:
# To generate a vandemonde matrix
# The columns of output matrix are powers of input vector
x = np.vander(np.array([1,2,3,5]), N=3, increasing=True)
x

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

In [ ]:
# Matrix
# Interpret the input as a matrix
x = np.array([[1,2], [3,4]])
m = np.mat(x)
print(x[0,0])
print(m[0,0])

# What this allows is allow you to use matrix operations on the numpy array


1
1


In [ ]:
# Basic operations
ref_array = 10*np.random.rand(3,4)
ref_array

array([[ 3.46824036,  7.67681693,  8.2756161 ,  7.32539822],
       [ 4.8000464 ,  6.80180895,  5.63463621,  8.51450354],
       [ 0.82627203,  0.50071077,  1.99507292,  6.79505002]])

In [ ]:
# Chaning array shape
ref_array = np.arange(10)
print(ref_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
ref_array = ref_array.reshape(5,2)
ref_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# To get a contiguous flattened array
np.ravel(ref_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Transposiing
ref_array = np.transpose(ref_array)
ref_array

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [ ]:
# if you want to expand shape of an array
ref_array = np.expand_dims(ref_array, axis=2)
ref_array

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

In [ ]:
# Joining arrays
a1 = np.random.randint(50, size=(4,3,2))
a2 = np.random.randint(50, size=(4,3,3))
print(a1, '\n', a2)

[[[14 37]
  [49  2]
  [37 23]]

 [[23 47]
  [47 46]
  [14 21]]

 [[27 10]
  [49 42]
  [45 23]]

 [[49 29]
  [22 20]
  [17 24]]] 
 [[[ 7 46 21]
  [39 32 11]
  [23 25  7]]

 [[22 39 20]
  [25 22  7]
  [15 30 20]]

 [[43 11  6]
  [29 39 44]
  [30 25  0]]

 [[14 35 12]
  [ 3 18  5]
  [41 48 44]]]


In [ ]:
np.concatenate((a1,a2), axis=2)

array([[[14, 37,  7, 46, 21],
        [49,  2, 39, 32, 11],
        [37, 23, 23, 25,  7]],

       [[23, 47, 22, 39, 20],
        [47, 46, 25, 22,  7],
        [14, 21, 15, 30, 20]],

       [[27, 10, 43, 11,  6],
        [49, 42, 29, 39, 44],
        [45, 23, 30, 25,  0]],

       [[49, 29, 14, 35, 12],
        [22, 20,  3, 18,  5],
        [17, 24, 41, 48, 44]]])

In [ ]:
# Stacking two same dimensional arrays along a new axis
a1 = np.random.randint(50, size=(4,3))
a2 = np.random.randint(50, size=(4,3))
print(a1, '\n', a2, '\n')

np.stack((a1, a2), axis=0)

[[ 1 41 42]
 [20 12 18]
 [ 0 25 22]
 [41 43 22]] 
 [[46 27  2]
 [48 10 27]
 [ 0  7 40]
 [35 11 20]] 



array([[[ 1, 41, 42],
        [20, 12, 18],
        [ 0, 25, 22],
        [41, 43, 22]],

       [[46, 27,  2],
        [48, 10, 27],
        [ 0,  7, 40],
        [35, 11, 20]]])

In [ ]:
# To stack arrays horizontally i.e. columsn wise)
np.hstack((a1, a2))

array([[ 1, 41, 42, 46, 27,  2],
       [20, 12, 18, 48, 10, 27],
       [ 0, 25, 22,  0,  7, 40],
       [41, 43, 22, 35, 11, 20]])

In [ ]:
# To stack arrays vertically i.e. row wise
np.vstack((a1, a2))

array([[ 1, 41, 42],
       [20, 12, 18],
       [ 0, 25, 22],
       [41, 43, 22],
       [46, 27,  2],
       [48, 10, 27],
       [ 0,  7, 40],
       [35, 11, 20]])

In [ ]:
# to create blocks of 